#!/usr/bin/env python3
"""Generate a UV-mapped textured cube test asset set for Ahamkara.

Produces a glTF 2.0 cube (POSITION + NORMAL + TEXCOORD_0 + UNSIGNED_INT indices)
with an external .bin, a small uncompressed 32-bit TGA albedo, and a `.mat`
material referencing the compiled texture. This exists so the PBR UV/texture
path has real authored content (the visual result is confirmed on a machine with
a display; here it is build-validated via the importer).

Usage:
    python3 tools/levelgen/gen_textured_cube.py

Writes (relative to repo root):
    assets/models/textured_cube.gltf
    assets/models/textured_cube.bin
    assets/textures/cube_albedo.tga
    assets/materials/cube.mat

The importer's minimal glTF loader reads FLOAT (5126) attributes and
UNSIGNED_INT (5125) indices correctly, so those component types are used.
"""

import json
import struct
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]

# 6 faces, 4 verts each (per-face normals + full-face UVs), 24 verts, 36 indices.
# Each face: (normal, [4 corner positions]) wound CCW; uv = (0,0)(1,0)(1,1)(0,1).
FACES = [
    ((0, 0, 1),  [(-1, -1, 1), (1, -1, 1), (1, 1, 1), (-1, 1, 1)]),    # +Z
    ((0, 0, -1), [(1, -1, -1), (-1, -1, -1), (-1, 1, -1), (1, 1, -1)]),# -Z
    ((1, 0, 0),  [(1, -1, 1), (1, -1, -1), (1, 1, -1), (1, 1, 1)]),    # +X
    ((-1, 0, 0), [(-1, -1, -1), (-1, -1, 1), (-1, 1, 1), (-1, 1, -1)]),# -X
    ((0, 1, 0),  [(-1, 1, 1), (1, 1, 1), (1, 1, -1), (-1, 1, -1)]),    # +Y
    ((0, -1, 0), [(-1, -1, -1), (1, -1, -1), (1, -1, 1), (-1, -1, 1)]),# -Y
]
UVS = [(0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 1.0)]


def build_geometry():
    positions, normals, uvs, indices = [], [], [], []
    for nrm, corners in FACES:
        base = len(positions) // 3
        for i, p in enumerate(corners):
            positions += [float(p[0]) * 0.5, float(p[1]) * 0.5, float(p[2]) * 0.5]
            normals += [float(nrm[0]), float(nrm[1]), float(nrm[2])]
            uvs += [UVS[i][0], UVS[i][1]]
        indices += [base + 0, base + 1, base + 2, base + 0, base + 2, base + 3]
    return positions, normals, uvs, indices


def write_gltf(out_gltf: Path, out_bin: Path):
    positions, normals, uvs, indices = build_geometry()
    pos_b = struct.pack(f"<{len(positions)}f", *positions)
    nrm_b = struct.pack(f"<{len(normals)}f", *normals)
    uv_b = struct.pack(f"<{len(uvs)}f", *uvs)
    idx_b = struct.pack(f"<{len(indices)}I", *indices)
    blob = pos_b + nrm_b + uv_b + idx_b
    out_bin.write_bytes(blob)

    vcount = len(positions) // 3
    o_pos, o_nrm, o_uv = 0, len(pos_b), len(pos_b) + len(nrm_b)
    o_idx = o_uv + len(uv_b)

    gltf = {
        "asset": {"version": "2.0", "generator": "ahamkara gen_textured_cube"},
        "scene": 0,
        "scenes": [{"nodes": [0]}],
        "nodes": [{"mesh": 0}],
        "meshes": [{"primitives": [{
            "attributes": {"POSITION": 0, "NORMAL": 1, "TEXCOORD_0": 2},
            "indices": 3,
            "material": 0,
        }]}],
        "materials": [{"pbrMetallicRoughness": {"baseColorFactor": [0.85, 0.45, 0.25, 1.0]}}],
        "buffers": [{"uri": out_bin.name, "byteLength": len(blob)}],
        "bufferViews": [
            {"buffer": 0, "byteOffset": o_pos, "byteLength": len(pos_b)},
            {"buffer": 0, "byteOffset": o_nrm, "byteLength": len(nrm_b)},
            {"buffer": 0, "byteOffset": o_uv, "byteLength": len(uv_b)},
            {"buffer": 0, "byteOffset": o_idx, "byteLength": len(idx_b)},
        ],
        "accessors": [
            {"bufferView": 0, "componentType": 5126, "count": vcount, "type": "VEC3"},
            {"bufferView": 1, "componentType": 5126, "count": vcount, "type": "VEC3"},
            {"bufferView": 2, "componentType": 5126, "count": vcount, "type": "VEC2"},
            {"bufferView": 3, "componentType": 5125, "count": len(indices), "type": "SCALAR"},
        ],
    }
    out_gltf.write_text(json.dumps(gltf, indent=2))


def write_tga(path: Path, size: int = 8):
    # Uncompressed 32-bit truecolor TGA, top-left origin, simple checkerboard.
    header = bytes([0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    size & 0xFF, (size >> 8) & 0xFF,
                    size & 0xFF, (size >> 8) & 0xFF,
                    32, 0x28])
    px = bytearray()
    for y in range(size):
        for x in range(size):
            light = (x // 2 + y // 2) % 2 == 0
            # BGRA
            if light:
                px += bytes([60, 115, 215, 255])
            else:
                px += bytes([40, 70, 130, 255])
    path.write_bytes(header + bytes(px))


def write_mat(path: Path):
    path.write_text(
        "# Generated by tools/levelgen/gen_textured_cube.py\n"
        "base_color=0.85 0.45 0.25 1\n"
        "metallic=0.0\n"
        "roughness=0.7\n"
        "albedo_texture=assets/compiled/textures/cube_albedo.aetex\n"
    )


def main() -> int:
    (REPO / "assets/models").mkdir(parents=True, exist_ok=True)
    (REPO / "assets/textures").mkdir(parents=True, exist_ok=True)
    (REPO / "assets/materials").mkdir(parents=True, exist_ok=True)
    write_gltf(REPO / "assets/models/textured_cube.gltf", REPO / "assets/models/textured_cube.bin")
    write_tga(REPO / "assets/textures/cube_albedo.tga")
    write_mat(REPO / "assets/materials/cube.mat")
    print("wrote textured_cube.gltf/.bin, cube_albedo.tga, cube.mat")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
