#!/usr/bin/env python3
"""Emit an Ahamkara `.lvl` level source from a canonical JSON level spec.

This is "Path A" of the authoring stack (see docs/vault/memory/decision-log.md):
turn a structured, human/agent-friendly JSON description of a level into the
`.lvl` text format the asset importer already compiles to `.aelevel`. The same
spec is the shared contract reused by Path B (the Blender generator).

JSON spec schema (all fields optional unless noted; 1:1 with `.lvl` capability):

    {
      "name": "My Level",
      "sky_color": [r, g, b],
      "ambient": [r, g, b],
      "gravity": 20.0,
      "skybox_material": "asset/id",   # omitted/empty -> not written
      "ground_material": "asset/id",   # omitted/empty -> not written
      "spawns": [
        {"pos": [x, y, z], "yaw": 0.0, "team": 1}
      ],
      "collision": [
        {"min": [min_x, min_z], "max": [max_x, max_z],
         "top_y": 0.0, "bottom_y": -0.5,
         "wall": false, "jump_through": false, "auto_step": true, "surface": 0}
      ],
      "meshes": [
        {"mesh": "asset/id-or-path", "material": "asset/id",
         "pos": [x, y, z], "yaw": 0.0, "pitch": 0.0, "roll": 0.0,
         "scale": [sx, sy, sz]}
      ]
    }

Usage:
    spec_to_lvl.py <spec.json> <out.lvl>
    spec_to_lvl.py --selftest <spec.json>   # emit, parse back, assert equality
"""

import json
import math
import sys
from pathlib import Path


def _num(value: float) -> str:
    return f"{float(value):g}"


def _flag(value: bool) -> str:
    return "true" if value else "false"


def spec_to_lvl_text(spec: dict, source_name: str = "") -> str:
    lines: list[str] = []
    lines.append("# Generated by tools/levelgen/spec_to_lvl.py - do not edit by hand.")
    if source_name:
        lines.append(f"# Source spec: {source_name}")
    lines.append("")

    lines.append(f"name={spec.get('name', 'Level')}")
    sky = spec.get("sky_color", [0.3, 0.4, 0.6])
    lines.append(f"sky_color={_num(sky[0])} {_num(sky[1])} {_num(sky[2])}")
    amb = spec.get("ambient", [0.05, 0.05, 0.1])
    lines.append(f"ambient={_num(amb[0])} {_num(amb[1])} {_num(amb[2])}")
    lines.append(f"gravity={_num(spec.get('gravity', 20.0))}")
    if spec.get("skybox_material"):
        lines.append(f"skybox_material={spec['skybox_material']}")
    if spec.get("ground_material"):
        lines.append(f"ground_material={spec['ground_material']}")

    spawns = spec.get("spawns", [])
    if spawns:
        lines.append("")
        lines.append("[spawn]")
        for s in spawns:
            p = s["pos"]
            line = f"{_num(p[0])} {_num(p[1])} {_num(p[2])} {_num(s.get('yaw', 0.0))}"
            if "team" in s:
                line += f" team={int(s['team'])}"
            lines.append(line)

    boxes = spec.get("collision", [])
    if boxes:
        lines.append("")
        lines.append("[collision]")
        for b in boxes:
            mn = b["min"]
            mx = b["max"]
            line = (
                f"{_num(mn[0])} {_num(mn[1])} {_num(mx[0])} {_num(mx[1])} "
                f"{_num(b.get('top_y', 0.0))} {_num(b.get('bottom_y', 0.0))} "
                f"wall={_flag(b.get('wall', False))} "
                f"jump_through={_flag(b.get('jump_through', False))} "
                f"auto_step={_flag(b.get('auto_step', True))} "
                f"surface={int(b.get('surface', 0))}"
            )
            lines.append(line)

    meshes = spec.get("meshes", [])
    if meshes:
        lines.append("")
        lines.append("[mesh]")
        for m in meshes:
            pos = m.get("pos", [0.0, 0.0, 0.0])
            scale = m.get("scale", [1.0, 1.0, 1.0])
            line = f"mesh_id={m['mesh']}"
            if m.get("material"):
                line += f" material_id={m['material']}"
            line += f" pos={_num(pos[0])} {_num(pos[1])} {_num(pos[2])}"
            line += f" yaw={_num(m.get('yaw', 0.0))}"
            line += f" pitch={_num(m.get('pitch', 0.0))}"
            line += f" roll={_num(m.get('roll', 0.0))}"
            line += f" scale_x={_num(scale[0])} scale_y={_num(scale[1])} scale_z={_num(scale[2])}"
            lines.append(line)

    lines.append("")
    return "\n".join(lines)


def parse_lvl(text: str) -> dict:
    """Parse a `.lvl` back into a normalized spec dict (for roundtrip checks)."""
    out: dict = {"spawns": [], "collision": [], "meshes": []}
    section = None
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("[") and line.endswith("]"):
            section = line[1:-1]
            continue
        if section is None:
            key, _, val = line.partition("=")
            key = key.strip()
            val = val.strip()
            if key in ("sky_color", "ambient"):
                out[key] = [float(x) for x in val.split()]
            elif key == "gravity":
                out[key] = float(val)
            else:
                out[key] = val
        elif section == "spawn":
            toks = line.split()
            spawn = {"pos": [float(toks[0]), float(toks[1]), float(toks[2])], "yaw": float(toks[3])}
            for t in toks[4:]:
                if t.startswith("team="):
                    spawn["team"] = int(t.split("=", 1)[1])
            out["spawns"].append(spawn)
        elif section == "collision":
            toks = line.split()
            box = {
                "min": [float(toks[0]), float(toks[1])],
                "max": [float(toks[2]), float(toks[3])],
                "top_y": float(toks[4]),
                "bottom_y": float(toks[5]),
            }
            for t in toks[6:]:
                k, _, v = t.partition("=")
                if k in ("wall", "jump_through", "auto_step"):
                    box[k] = v == "true"
                elif k == "surface":
                    box[k] = int(v)
            out["collision"].append(box)
        elif section == "mesh":
            toks = line.split()
            mesh: dict = {}
            i = 0
            while i < len(toks):
                k, _, v = toks[i].partition("=")
                if k == "mesh_id":
                    mesh["mesh"] = v
                elif k == "material_id":
                    mesh["material"] = v
                elif k == "pos":
                    mesh["pos"] = [float(v), float(toks[i + 1]), float(toks[i + 2])]
                    i += 2
                elif k in ("yaw", "pitch", "roll", "scale_x", "scale_y", "scale_z"):
                    mesh[k] = float(v)
                i += 1
            scale = [mesh.pop("scale_x", 1.0), mesh.pop("scale_y", 1.0), mesh.pop("scale_z", 1.0)]
            mesh["scale"] = scale
            out["meshes"].append(mesh)
    return out


def _close(a: float, b: float) -> bool:
    return math.isclose(a, b, rel_tol=1e-5, abs_tol=1e-5)


def selftest(spec_path: Path) -> int:
    spec = json.loads(spec_path.read_text())
    text = spec_to_lvl_text(spec, spec_path.name)
    parsed = parse_lvl(text)

    failures: list[str] = []

    if parsed.get("name") != spec.get("name", "Level"):
        failures.append("name mismatch")
    if not _close(parsed.get("gravity", 20.0), spec.get("gravity", 20.0)):
        failures.append("gravity mismatch")

    if len(parsed["spawns"]) != len(spec.get("spawns", [])):
        failures.append("spawn count mismatch")
    if len(parsed["collision"]) != len(spec.get("collision", [])):
        failures.append("collision count mismatch")
    if len(parsed["meshes"]) != len(spec.get("meshes", [])):
        failures.append("mesh count mismatch")

    for got, want in zip(parsed["meshes"], spec.get("meshes", []), strict=False):
        if got.get("mesh") != want.get("mesh"):
            failures.append(f"mesh id mismatch: {got.get('mesh')} != {want.get('mesh')}")
        wp = want.get("pos", [0.0, 0.0, 0.0])
        gp = got.get("pos", [0.0, 0.0, 0.0])
        if not all(_close(a, b) for a, b in zip(gp, wp, strict=False)):
            failures.append("mesh pos mismatch")

    if failures:
        for f in failures:
            print(f"spec_to_lvl: selftest FAIL: {f}", file=sys.stderr)
        return 1
    print(
        f"spec_to_lvl: selftest OK: {spec_path.name} ({len(parsed['meshes'])} mesh, "
        f"{len(parsed['spawns'])} spawn, {len(parsed['collision'])} collision)"
    )
    return 0


def main(argv: list[str]) -> int:
    if len(argv) == 3 and argv[1] == "--selftest":
        return selftest(Path(argv[2]))
    if len(argv) != 3:
        print(__doc__)
        return 2
    spec_path = Path(argv[1])
    out_path = Path(argv[2])
    spec = json.loads(spec_path.read_text())
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(spec_to_lvl_text(spec, spec_path.name))
    print(f"spec_to_lvl: wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
